### ISSUE TITLE
SCS IaaS Standard flavors and Flavor naming discussion

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/standards#271]
The SCS community had agreed on a standard flavor naming scheme and standard flavors back in 2021. The discussion was somewhat lengthy. In the process a document explaining the [logic](https://github.com/SovereignCloudStack/standards/blob/main/Drafts/flavor-naming-strategy.md) and a [v1 flavor naming specification](https://github.com/SovereignCloudStack/standards/blob/main/Drafts/flavor-naming.md) were agreed upon.
This was considered to be a mandatory SCS standard on the IaaS layer since then.
The software engineering rule that something that is not tested is (almost) always broken also hit us here: In summer 2022, we observed SCS cloud providers not implementing the standard fully correctly. Since then a [checker tool](https://github.com/SovereignCloudStack/standards/blob/main/Tests/iaas/flavor-naming/flavor-name-check.py) has been created that can validate a flavor or generate a flavor name from parameters.
A tool to [check all flavors](https://github.com/SovereignCloudStack/standards/blob/main/Tests/iaas/flavor-naming/flavor-names-openstack.py) has been added and it is called from the [compliance check test suite](https://github.com/SovereignCloudStack/standards/blob/main/Tests/scs-compliance-check.py) whose results are displayed on [github](https://github.com/SovereignCloudStack/standards). Our CSP partners were successful in becoming fully compliant in fall 2022.

Unfortunately, the original v1 proposal contains `:` in their names and certain k8s tools (OpenShift) use the infra flavor names as labels in Kubernetes, where `:` is not allowed. This [causes trouble](https://github.com/SovereignCloudStack/standards/issues/190) running OpenShift on top of SCS IaaS with v1 flavor names. A [v2 scheme](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v2-flavor-naming.md) was [discussed](https://github.com/SovereignCloudStack/standards/issues/192) and created.

Unfortunately, the migration causes some [pain](https://github.com/SovereignCloudStack/standards/issues/228) for providers. In the Nuremberg Hackathon, we found out that not all SCS IaaS providers have a clear commitment to implement the v2 flavors and work with us to minimize the pain. This would be unfortunate, stripping SCS from one of the benefits where flavor related pain points for migrations and/or simultaneous multi-cloud deployments are addressed.

Currently, the [SCS compliance specification](https://github.com/SovereignCloudStack/standards/blob/main/Tests/scs-compatible.yaml) allows for both v1 and v2 compliance and the clouds are checked for both. However, this is currently scheduled to end on October 2023. The SCS project leader wants to have an agreed strategy long before October comes and has thus written a discussion document: [Why do we need to standardize flavors and flavor names](https://input.scs.community/Why-Standardized-Flavors-And-Names).

The document breaks down the discussion into 12 suggestions. Some of them might not be controversial at all, some may be.
The author would like to invite everyone to comment on the suggestions. He would also like to suggest that anyone expressing his/her agreement or disagreement or extra consideration does relate it to a specific suggestion (or set of suggestions). For this, issues on each suggestion have been created, so the discussion does not get confusing.
Of course the author might have overlooked important aspects for this discussion, so it is possible that discussion topics beyond the 12 suggestions pop up. Additional issues might be opened up and linked here then.
Global discussion (comments affecting many of the suggestions at once) can happen here, would still be good to be precise on what aspect is being commented on.

- [ ] https://github.com/SovereignCloudStack/standards/issues/272
- [ ] https://github.com/SovereignCloudStack/standards/issues/273
- [ ] https://github.com/SovereignCloudStack/standards/issues/274
- [ ] https://github.com/SovereignCloudStack/standards/issues/275
- [ ] https://github.com/SovereignCloudStack/standards/issues/276
- [ ] https://github.com/SovereignCloudStack/standards/issues/277
- [ ] https://github.com/SovereignCloudStack/standards/issues/278
- [ ] https://github.com/SovereignCloudStack/standards/issues/279
- [ ] https://github.com/SovereignCloudStack/standards/issues/280
- [ ] https://github.com/SovereignCloudStack/standards/issues/281
- [ ] https://github.com/SovereignCloudStack/standards/issues/282
- [ ] https://github.com/SovereignCloudStack/standards/issues/283

**Comment by tibeer** [comment]
Just my two cents:

1. Agreed
2. No opinion
3. Agreed
4. Agreed (As nobody prevents CSP's to create their own, additional flavor names, I see no problem with the SCS prefix)
5. Agreed
6. Agreed
7. Agreed (As nobody prevents CSP's to create their own, additional flavor names, I see no problem with the SCS prefix)
8. Agreed
9. No opinion (Though I might trow in that this enforces SCS providers, especially if this runs in-house, to provide some sort of local storage/hyperconverged nodes. Might be undesireable if you pay for a huge netapp cluster already and you don't have the requirement to run k8s clusters; but as already said: I have no opinion on that topic due to lack of information)
10. Agreed
11. Agreed
12. Agreed

**Comment by garloff** [comment]
Suggestion 3: Number of flavors discussion.
- Many flavors create work in billing system (mapping flavors to prices)
- Many flavors (100) create usability challenges in horizon

Idea: Split mandatory list into a mandatory and recommended list.

**Comment by garloff** [comment]
26 seems completely reasonable (and convenient for user, @tibeer), but these are just general-purpose, if we start with special features, we'll could have many more.

**Comment by garloff** [comment]
Recommendation 4: cryptic names
SCS-4V-16-50 vs. SCS-standard-medium-V-50
SCS-4V-16 vs. SCS-standard-medium-V

**Comment by garloff** [comment]
Long-term goal: Names don't matter any more, as we select flavors by discoverable properties (and the tools all have nice support for that, which is not currently the case). Agreement.

Medium-term: PS prefers the speaking names "-standard-medium" over "-4V-16", the SCS team does not.

**Comment by garloff** [comment]
A good approach to avoid the decision would be to have flavor aliases. Could be implemented by extra API (in front of nova) or by a nova improvement. (PoC exists!)
We could then even support a scheme that emulates AWS, StackIT, .... (@tibeer).

**Comment by garloff** [comment]
PS: Invest into discoverability and tool support for it to get quickly to a state where names are irrelevant instead of name aliases.
