### ISSUE TITLE
Tracking and documenting compliance of clouds with SCS certificates

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#346]
As a cloud customer, I want to know compliance history and level of clouds with SCS certificates so that I can evaluate different providers with respect to their reliability.

## Definition of Done:

The following questions MUST be answered

- [x] What is the frequency of the automated (or manual?) checks?
- [x] What are the consequences of failed checks? 
- [x] Do we want to revoke the cert and if so, under which circumstances? 
- [x] How do we make check results & revokation of certs transparent for customers?

**Comment by mbuechse** [comment]
Quoting the SIG minutes of the 2023-09-21 meeting (that I unfortunately couldn't make):

- In What frequency is it checked?
    - Automated checks: Nightly
    - Manual checks: Needs discussion. Thoughts
        - 4 months (like k8s recency)
        - 3 months (like LE certs)
        - Badge will contain validity in text and in digital signature
- Currently, do we really want to de-validate the cert. when the compliance check tool fails?
    - a one time fail could be temporary, can not lead to a cert invalidation
    - longer-term fails:
        - please fix notification (after 2nd fail)
        - make this transparent to customer
            - https://docs.scs.community/standards
        - "SLA" type measurement: 99.x% of time compliance :-)
    - Proposal
        - cert agreement includes our right to measure and publish the current and historic results on a public page 
        - official invalidation would then only need to happen after a longer period 
            - CRL, generated automatically after a certain threshold has been exceeded (automated warnings generated before this happens)
    - Issue to be created and ADR to be written (AI: @mbuechse/@anjastrunk/@cah-baum)
        - Enhances or relates to scs-0003

**Comment by mbuechse** [comment]
I think this issue is more or less a duplicate of #337. I think I shall integrate the two within the open (draft) PR (#239).

**Comment by mbuechse** [comment]
Will be resolved together with #337.
