### ISSUE TITLE
[Other] Evaluate costs of making a cluster SCS compliant 

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#426]
Epic issue to evaluate costs to make existing, non-compliant OpenStack and K8S cluster SCS compliant. In doing so, we set up a non-compliant cluster with the open source life Lifecycle Management Tool for OpenStack and K8S [Yaook](https://yaook.cloud/).

This issue acts as epic.

**General** 

- [ ]  https://github.com/SovereignCloudStack/standards/issues/414

**IaaS**

- [ ]  https://github.com/SovereignCloudStack/standards/issues/415
- [ ] https://github.com/SovereignCloudStack/standards/issues/416
- [ ] https://github.com/SovereignCloudStack/standards/issues/417
- [ ] https://github.com/SovereignCloudStack/standards/issues/418
- [ ] https://github.com/SovereignCloudStack/standards/issues/419

**KaaS**

- [ ] https://github.com/SovereignCloudStack/standards/issues/420
- [ ] https://github.com/SovereignCloudStack/standards/issues/421
- [ ] https://github.com/SovereignCloudStack/standards/issues/422
- [ ] https://github.com/SovereignCloudStack/standards/issues/423
- [ ] https://github.com/SovereignCloudStack/standards/issues/424
- [ ] https://github.com/SovereignCloudStack/standards/issues/425

**Comment by anjastrunk** [comment]
> I created a document to show what is necessary to make a Yaook cluster (OpenStack) compliant with SCS. It basically combines the standards into an easy to read document (and make it a bit easier). Some information get lost, but I also reference to the original documents, so every reader knows where to go if questions arise.
> 
> I'm not entirely sure where to post this document to keep the SCS-Team in the loop on this, but I think I will just create a branch that will never be merged. The most current version can always be found in our internal infrastructure, since the updates here will maybe be behind 1-2 days.
> 
> Edit: https://github.com/SovereignCloudStack/standards/compare/do-not-merge/scs-compliant-yaook contains the documents.

Good idea. General outcomes on how to make arbitrary OpenStack/KaaS cluster SCS compliant, should be documented in the corresponding issue, as listed in this epic. Furthermore, we should write blog articles, whenever a topic is value-added for CSPs and SCS community.

**Comment by cah-hbaum** [comment]
I started to setup an independent K8s cluster that will be used to test the K8s standards. The cluster is already up and running, next step is to apply the standards.

**Comment by cah-hbaum** [comment]
I finally created the k8s cluster from `yaook/k8s`. This took a bit longer, since the latest release (5.1) generated some problems on my end (I will explain this further in the ["Debugging Issue"](https://github.com/SovereignCloudStack/standards/issues/556)).

Nonetheless, I could create a cluster and will check this now for conformance with the SCS standards, especially `SCS Compatible KaaS v2`.

Further information can be found in the issues regarding this.
