### ISSUE TITLE
EPIC: Certification and Certification Process

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#566]
## Certificates

- [x] https://github.com/SovereignCloudStack/standards/issues/347
- [ ] https://github.com/SovereignCloudStack/standards/issues/338

## Certification Issuing & Compliance Check

- [x] https://github.com/SovereignCloudStack/standards/issues/337
- [x] https://github.com/SovereignCloudStack/standards/issues/459
- [x] https://github.com/SovereignCloudStack/standards/issues/450
- [x] https://github.com/SovereignCloudStack/standards/issues/346
- [ ] https://github.com/SovereignCloudStack/standards/issues/442
- [ ] https://github.com/SovereignCloudStack/standards/issues/381
- [ ] https://github.com/SovereignCloudStack/standards/issues/359

## CI/CD Pipeline

- [x] https://github.com/SovereignCloudStack/standards/issues/477
- [x]  https://github.com/SovereignCloudStack/standards/issues/476
- [x] https://github.com/SovereignCloudStack/standards/issues/447
- [x] https://github.com/SovereignCloudStack/standards/issues/402
- [x] https://github.com/SovereignCloudStack/standards/issues/316
