### ISSUE TITLE
[EPIC] KaaS standards

### ISSUE THREAD

**Issue by martinmo** [SovereignCloudStack/standards#615]
#### Standardization

- [ ] https://github.com/SovereignCloudStack/issues/issues/636
- [ ] https://github.com/SovereignCloudStack/standards/issues/494
- [ ] https://github.com/SovereignCloudStack/standards/issues/535
- [ ] https://github.com/SovereignCloudStack/standards/issues/475
- [x] https://github.com/SovereignCloudStack/issues/issues/414
- [x] https://github.com/SovereignCloudStack/standards/issues/481

#### Conformance test implementation

- [ ] https://github.com/SovereignCloudStack/standards/issues/489
- [ ] https://github.com/SovereignCloudStack/standards/issues/526

#### Conformance test implementation

- [ ] https://github.com/SovereignCloudStack/issues/issues/549

### Possible future standards and ADRs

- [ ] https://github.com/SovereignCloudStack/standards/issues/234
- [ ] https://github.com/SovereignCloudStack/standards/issues/324
- [ ] https://github.com/SovereignCloudStack/issues/issues/421
- [ ] https://github.com/SovereignCloudStack/issues/issues/420
- [ ] https://github.com/SovereignCloudStack/issues/issues/419
- [ ] https://github.com/SovereignCloudStack/issues/issues/418
- [ ] https://github.com/SovereignCloudStack/issues/issues/417
- [ ] https://github.com/SovereignCloudStack/issues/issues/416

### Links

* [KaaS standards](https://docs.scs.community/standards/kaas/)
* [Certificate scope *SCS Compatible KaaS*](https://docs.scs.community/standards/scs-compatible-kaas)

**Comment by mbuechse** [comment]
We do have this one already: https://github.com/SovereignCloudStack/issues/issues/181
But yours is more like a roadmap, so not too bad either!

**Comment by martinmo** [comment]
Thanks for the hint! I linked the other epic and added some missing tasks to the list here. I agree that having this roadmap style issue has value, after all I felt the need to create it, but I didn't intend to duplicate stuff :( Maybe we can focus on this issue here and close the other one – IMHO the standards repo is the right place anyway.
