### ISSUE TITLE
Make sonobuoy golang framework useable for production

### ISSUE THREAD

**Issue by tonifinger** [SovereignCloudStack/standards#735]
As described in DR, [scs-0200-v1-using-sonobuoy-for-kaas-conformance-tests.md](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0200-v1-using-sonobuoy-for-kaas-conformance-tests.md), it was decided to use sonobuoy as framework to deploy tests to Kubernetes clusters.

The current Sonobuoy setup within the repository was merely a PoC. We want to make it ready for production use.

The following must therefore be adjusted/implemented:

####  PREREQUISITES:

- [x] Implementation of the Golang test framework in accordance with the PoC (see: [kaas-sonobuoy-go-example-e2e-framework](https://github.com/SovereignCloudStack/standards/tree/main/Tests/kaas/kaas-sonobuoy-go-example-e2e-framework) )
- [ ] ZuuL job to create the Sonobuoy image and upload it to the Github container registry
  - apply multi platform builds using the multi-arch setup
  - rework plugin config to dynamically chose image tag
  - check go sum file

#### TASKS

- [x]  multi-arch support for `arm64` and `amd64` #758 
- [x]  Upgrade golang version: #747
- [ ] Write documentation on how you can contribute new tests. As part of [docs/issues/201](https://github.com/SovereignCloudStack/docs/issues/201)
- [ ] Update the DR to describe the current setup
- [ ] Zuul job to run the conformance test: #710 

#### OPTIONAL

- [ ] Write documentation on how a User(not a developer) can run the sonobuoy tests on its own.
  - currently blocked by the image not beeing build so far.
- [ ] apply golang linter https://golangci-lint.run/

**Comment by anjastrunk** [comment]
@tonifinger How is the status here. Can this issue be closed or are there still open tasks?
